# voucher_standards/silver_v1/standard.toml
# ==============================================================================
# IMMUTABLE-ZONE
# ==============================================================================
[immutable.identity]
uuid = "SILVER-PAYMENT-V1-2025-09"
name = "Silber-Umlauf-Gutschein"
abbreviation = "Oz"

[immutable.blueprint]
unit = "Unzen"
primary_redemption_type = "goods_or_services"
collateral_type = "Physisches Edelmetall"

[immutable.features]
allow_partial_transfers = true
balances_are_summable = true
amount_decimal_places = 4
privacy_mode = "flexible"

allowed_t_types = ["init", "transfer", "split", "merge"]
[immutable.issuance]
validity_duration_range = ["P1Y", "P10Y"]
issuance_minimum_validity_duration = "P0Y"
additional_signatures_range = [0, 3]
allowed_signature_roles = ["guarantor"]

[immutable.transfer]
requires_recipient_signature = true

# ==============================================================================
# MUTABLE-ZONE
# ==============================================================================
[mutable.metadata]
issuer_name = "Silber Standard Council"
homepage_url = "https://example.com/silver-standard-infos"
documentation_url = "https://example.com/silver-standard-docs"
keywords = [
    "asset-backed",
    "silver",
    "precious-metal",
    "payment",
]

[mutable.app_config]
default_validity_duration = "P5Y"
server_history_retention = "P3M"

[mutable.i18n.descriptions]
de = "Dieser Gutschein dient als Zahlungsmittel für Waren oder Dienstleistungen im Wert von {{amount}} Unzen Silber."
en = "This voucher serves as a means of payment for goods or services worth {{amount}} ounces of silver."

[mutable.i18n.footnotes]
de = "Besichert durch physisch hinterlegtes Silber."

[mutable.i18n.collateral_descriptions]
de = "Der Gutschein ist durch die entsprechende Menge an physischem Silber besichert. Nur in Notfällen einlösbar, wenn der Aussteller die versprochene Leistung nicht erbringen kann."

[signature]
# Die `did:key` des Herausgebers, die seinen öffentlichen Schlüssel enthält.
issuer_id = "0:riw@did:key:z6Mki8QqVMb66hjtTwcceVXbZuSHTk61jqiprRvEhuotZmSA"

# Die finale Base58-kodierte Ed25519-Signatur des kanonisierten Inhalts (ohne diesen Block).
signature = "2hcGYhnZdjyUFJLYdDZzbQzDqkk5p5do8bbejLBg1k6tNtpp1pv87XFeSKrbwbHGAPBBKfT7tJGnVthSwkzwYWLG"
