# voucher_standards/minuto_v1/standard.toml
# ==============================================================================
# IMMUTABLE-ZONE
# ==============================================================================
[immutable.identity]
uuid = "MINUTO-V1-2025-09"
name = "Minuto-Gutschein"
abbreviation = "Minuto"

[immutable.blueprint]
unit = "Minuto"
primary_redemption_type = "goods_or_services"
collateral_type = "personal_guarantee"

[immutable.features]
allow_partial_transfers = true
balances_are_summable = true
amount_decimal_places = 0
privacy_mode = "flexible"

allowed_t_types = ["init", "transfer", "split", "merge"]
[immutable.issuance]
validity_duration_range = ["P1Y", "P10Y"]
issuance_minimum_validity_duration = "P3Y"
additional_signatures_range = [2, 2]
allowed_signature_roles = ["guarantor"]

[immutable.transfer]
requires_recipient_signature = true

[immutable.custom_rules.gender_balance_male]
expression = "Voucher.signatures.filter(s, s.role != 'creator' && has(s.details.gender) && s.details.gender == '1').size() == 1"
message = "Gemäß ISO 5218 wird genau ein männlicher (1) Bürge benötigt."

[immutable.custom_rules.gender_balance_female]
expression = "Voucher.signatures.filter(s, s.role != 'creator' && has(s.details.gender) && s.details.gender == '2').size() == 1"
message = "Gemäß ISO 5218 wird genau eine weibliche (2) Bürgin benötigt."

# ==============================================================================
# MUTABLE-ZONE
# ==============================================================================
[mutable.metadata]
issuer_name = "Minuto Community Council"
homepage_url = "https://minuto.org/standard-info"
documentation_url = "https://github.com/minuto/standards/tree/main/minuto_v1"
keywords = [
    "community-currency",
    "time-based",
    "mutual-credit",
    "b2b",
]

[mutable.app_config]
default_validity_duration = "P5Y"
round_up_validity_to = "P1Y"
server_history_retention = "P3M"

[mutable.i18n.descriptions]
de = "Ein Gutschein für Waren oder Dienstleistungen im Wert von {{amount}} Minuten qualitativer Leistung."
en = "A voucher for goods or services worth {{amount}} minutes of quality performance."

[mutable.i18n.footnotes]
de = "Gutschein-Nutzung nur für Mitspieler/innen."

[signature]
# Die `did:key` des Herausgebers, die seinen öffentlichen Schlüssel enthält.
issuer_id = "0:riw@did:key:z6Mki8QqVMb66hjtTwcceVXbZuSHTk61jqiprRvEhuotZmSA"

# Die finale Base58-kodierte Ed25519-Signatur des kanonisierten Inhalts (ohne diesen Block).
signature = "5fTR7iLteURNTBQLf6yL66BAvf1BGXGNsR1ewnVNxkVrEehyWYbBkxNT9Cwh7iy75aqoGhd8RnYQoqLnc1Z9YmEL"
